steps:
  - key: "sentence"
    label: ":snake: sentence (max_char=20)"
    agents:
      queue: "default"
    plugins:
      - docker#v5.10.0:
          image: "python:3.13"
    command:
      - pip install -e .
      - python -c "import loremipsum; print(loremipsum.sentence(max_char=20))" > result.txt
    artifact_paths:
      - "result.txt"

  - key: "annotate_sentence"
    label: ":memo: annotate sentence"
    depends_on: "sentence"
    agents:
      queue: "default"
    command:
      - buildkite-agent artifact download "result.txt" .
      - buildkite-agent annotate --style info --context sentence "$(cat result.txt)"

  - key: "paragraph"
    label: ":snake: paragraph (max_char=100)"
    depends_on: "sentence"   # ensures it runs only if sentence succeeded
    agents:
      queue: "default"
    plugins:
      - docker#v5.10.0:
          image: "python:3.13"
    command:
      - pip install -e .
      - python -c "import loremipsum; print(loremipsum.paragraph(max_char=100))" > paragraph.txt
    artifact_paths:
      - "paragraph.txt"

  - key: "annotate_paragraph"
    label: ":memo: annotate paragraph"
    depends_on: "paragraph"
    agents:
      queue: "default"
    command:
      - buildkite-agent artifact download "paragraph.txt" .
      - buildkite-agent annotate --style success --context paragraph "$(cat paragraph.txt)"